services:
  - type: web
    name: decasa-api
    env: docker
    rootDir: decasa-api
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_TIMEZONE
        value: America/Bogota
      - key: SESSION_DRIVER
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: CACHE_STORE
        value: database
      - key: BROADCAST_CONNECTION
        value: reverb
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_LEVEL
        value: warning
